# This document represents a 2D truss in static equilibrium
# this is test case 1

version = 0
name = "test case 1"
description = "The first test case used to solve statices problems, checked by hand!"
debug = true
write-file = false

# unused (for now?):
# weight = { applied = false, type = "density", magnitude = 1 } # unused, maybe remove

# defining a point: "name", "definition strategy", <x or r>, <y or theta>
points = [
    ["A", "Origin"],
    ["B", "Cartesian", 2, 0],
    ["C", "Polar", 2, 60],
]

members = [
    ["A", "B"],
    ["A", "C"],
    ["B", "C"],
]

loads = [
    ["C", 50, "Down"],
    ["A", 25, "Polar", 90],
    ["B", 25, "Up"],
]

# currently only accepts pin and roller
supports = [
    #["C", "Pin"],
    #["A", "Roller", "Down]
]