# version, name = "", description = "", debug = false, write-file = false,
version = 0
name = "Problem 2 :)"
description = "THIS PROBLEM IS NOT IN EQUILIBRIUM!!! DO NOT USE !!!"
debug = false
write-file = false

# DO NOT USE!!!!! This is a broken problem to check what happens with bad inputs

# defining a point: "name", "definition strategy", <x or r>, <y or theta>
points = [
    ["A", "Origin"],
    ["B", "Cartesian", 0, 2],
    ["C", "Cartesian", 2, 0],
]

# members = [ [point name, point name], ... ]
members = [
    ["A", "B"],
    ["A", "C"],
    ["B", "C"],
    ["A", "D"],
    ["C", "D"],
]

# loads = [ [point name, direction, <angle>], ...]
loads = [
    ["B", 50, "Right"],
    ["D", 50, "Right"],
    ["C", 100, "Left"],
]

# currently only accepts pin and roller
supports = [
    #["C", "Pin"],
    #["A", "Roller", "Down]
]